[System.Serializable]
public enum Channel
{
    PLAYER_SOUND_JUMP,
    PLAYER_SOUND_FRUIT_PICKUP,
    ENEMY_SOUND_ENEMYDEATH,
    PLAYER_SOUND_CHECKPOINT,
    PLAYER_SOUND_FINISH,
    PLAYER_SOUND_DEATH,
    MUSIC
}